language: android
android:
  components:
    - build-tools-29.0.3
    - android-29
    - android-21
    - add-on
    - extra
    - platform-tools
    - tools
    - extra-google-googleplayservices
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-29
    - sys-img-armeabi-v7a-android-21

before_install:
  - yes | sdkmanager "platforms;android-29"

script: ./gradlew :app:build

env:
  global:
    - MALLOC_ARENA_MAX=2
sudo: required

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a -s "768x1280"
  - emulator -avd test -no-audio -no-window &
  - adb wait-for-device
  - adb shell input keyevent 82 &

notifications:
  email:
    recipients:
    - myemail@address.com
    on_success: always
    on_failure: always